name: Latest YouTube Videos
on:
  schedule:
    # Runs 1AM every Sunday cron schedule expression
    - cron: '0 1 * * 0'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with YouTube videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCFNwcJUO-5aeU3b7-mh3kdw"